# â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
# â”‚        Starship Prompt for Lars ğŸ›°ï¸         â”‚
# â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜
# Use the Catppuccin Macchiato palette
palette = "catppuccin_macchiato"

add_newline = false
format = "\n$os$username$hostname$directory$git_branch$git_status$python$nodejs$package$cmd_duration$line_break$character"

[os]
style = "bold lavender"
disabled = false

[username]
show_always = true
style_user = "bold peach"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold sky"
format = "[@$hostname]($style) "

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ï ½"
read_only_style = "bold red"

[git_branch]
symbol = "ï˜ "
style = "bold mauve"
format = "on [$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "([$all_status$ahead_behind]($style))"

[python]
symbol = "îˆµ "
style = "bold yellow"
format = '[$symbol$version]($style) '

[nodejs]
symbol = "îœ˜ "
style = "bold green"
format = '[$symbol$version]($style) '

[package]
symbol = "ğŸ“¦ "
style = "bold peach"
format = "[$symbol$version]($style) "

[cmd_duration]
min_time = 1000
format = " ğŸ•’ [$duration](bold yellow)"

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
